# Generated by Django 4.0 on 2023-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department_name',
            field=models.CharField(choices=[('d1', 'Computer'), ('d2', 'Mechanical'), ('d3', 'E&T')], max_length=5, null=True),
        ),
    ]
