# Generated by Django 4.0 on 2023-11-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_name',
            field=models.CharField(choices=[('comp', 'Computer'), ('mech', 'Mechanical'), ('et', 'E&T')], default='Comp', max_length=7),
        ),
    ]
