# Generated by Django 4.0 on 2023-11-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_name',
            field=models.CharField(choices=[('comp', 'Computer'), ('mech', 'Mechanical'), ('et', 'E&T')], max_length=20, null=True),
        ),
    ]
