# Generated by Django 4.0 on 2023-11-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_uploadfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploaded_at',
        ),
    ]
